server:
  port: 8189
  servlet:
    context-path: /application
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./mydatabase;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibertnate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2